### ISSUE TITLE
RangeError

### ISSUE THREAD

**Issue by Enuomis** [FrogTheFrog/steam-gyro-for-cemuhook#23]
As soon as I open Cemu or pad test, I get this error, can you help me figure it out please?

2019-09-07T00:39:45.684Z] RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received -896183418
    at checkInt (internal/buffer.js:35:11)
    at writeU_Int32LE (internal/buffer.js:513:3)
    at Buffer.writeUInt32LE (internal/buffer.js:526:10)
    at t.UdpServer.handleReport (C:\Users\Simon\AppData\Local\Temp\nstCF0E.tmp\app\resources\app.asar\dist\main.bundle.js:18:113282)
    at t.controllers.(anonymous function).subscription.add.add.e.onDualshockData.subscribe.e [as _next] (C:\Users\Simon\AppData\Local\Temp\nstCF0E.tmp\app\resources\app.asar\dist\main.bundle.js:18:108900)
    at t.__tryOrUnsub (C:\Users\Simon\AppData\Local\Temp\nstCF0E.tmp\app\resources\app.asar\dist\main.bundle.js:16:3215)
    at t.next (C:\Users\Simon\AppData\Local\Temp\nstCF0E.tmp\app\resources\app.asar\dist\main.bundle.js:16:2360)
    at t._next (C:\Users\Simon\AppData\Local\Temp\nstCF0E.tmp\app\resources\app.asar\dist\main.bundle.js:16:1412)
    at t.next (C:\Users\Simon\AppData\Local\Temp\nstCF0E.tmp\app\resources\app.asar\dist\main.bundle.js:16:1083)
    at t.next (C:\Users\Simon\AppData\Local\Temp\nstCF0E.tmp\app\resources\app.asar\dist\main.bundle.js:16:8340)

**Comment by Enuomis** [comment]
For anyone else having the same issue, I don't know if that's the solution but i turned Full Sync at GX2DrawDone() on and the issue seems to be gone.

EDIT : Nope, not the solution...
